// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js";
import type {
  ResolvingMetadata,
  ResolvingViewport,
} from "next/types.js";

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default:
    | React.ComponentType<
        { params: Promise<ParamMap[Route]> } & Record<string, unknown>
      >
    | ((
        props: { params: Promise<ParamMap[Route]> } & Record<string, unknown>
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) => Promise<Record<string, unknown>[]> | Record<string, unknown>[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & Record<string, unknown>,
    parent: ResolvingMetadata
  ) => Promise<Record<string, unknown>> | Record<string, unknown>;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & Record<string, unknown>,
    parent: ResolvingViewport
  ) => Promise<Record<string, unknown>> | Record<string, unknown>;
  metadata?: Record<string, unknown>;
  viewport?: Record<string, unknown>;
};

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default:
    | React.ComponentType<LayoutProps<Route>>
    | ((
        props: LayoutProps<Route>
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) => Promise<Record<string, unknown>[]> | Record<string, unknown>[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & Record<string, unknown>,
    parent: ResolvingMetadata
  ) => Promise<Record<string, unknown>> | Record<string, unknown>;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & Record<string, unknown>,
    parent: ResolvingViewport
  ) => Promise<Record<string, unknown>> | Record<string, unknown>;
  metadata?: Record<string, unknown>;
  viewport?: Record<string, unknown>;
};

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific;
  const handler = {} as typeof import("../app/page.tsx");
  type __Check = __IsExpected<typeof handler>;
  /* eslint-disable-next-line @typescript-eslint/ban-ts-comment */
  /* @ts-ignore */
  type __Unused = __Check;
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific;
  const handler = {} as typeof import("../app/layout.tsx");
  type __Check = __IsExpected<
    typeof handler & { metadata: Record<string, unknown> }
  >;
  /* eslint-disable-next-line @typescript-eslint/ban-ts-comment */
  /* @ts-ignore */
  type __Unused = __Check;
}
