import LocationNavbar from "@/components/LocationNavbar";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Locations",
  description: "Generated by create next app",
};

export default function LocationsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header>
        <p className="text-center text-xs sm:text-sm text-white bg-primary py-1.5 px-2">
          New service! Luggage transport anywhere in France and Europe.{" "}
          <Link href="/" className="underline">
            Click here
          </Link>
        </p>
      </header>
      <LocationNavbar />
      <main>{children}</main>
    </>
  );
}
